import os
import sys
import json
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

def test_provider_connectivity():
    print("=" * 60)
    print("STANDALONE AI PROVIDER CONNECTIVITY & GENERATION TEST")
    print("=" * 60)

    try:
        from dotenv import load_dotenv
        load_dotenv()
    except Exception:
        pass

    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("AI_API_KEY")
    model_env = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

    print(f"[AI DEBUG] AI provider configured: True (Google Gemini REST API)")
    print(f"[AI DEBUG] AI API key configured: {bool(api_key)}")
    print(f"[AI DEBUG] AI model configured: {model_env}")

    if not api_key:
        print("[AI ERROR] No API key found in environment!")
        sys.exit(1)

    from services.ai_service import GeminiAIProvider, AIGenerationError

    test_input = {
        "learning_context": {
            "domain": {"id": "python", "name": "Python Programming"},
            "learning_goal": {"type": "conceptual_understanding", "description": "Master core Python fundamentals"},
            "curriculum": {
                "areas": [
                    {"id": "topic_variables", "name": "Variables", "type": "topic"},
                    {"id": "topic_loops", "name": "Loops", "type": "topic"},
                    {"id": "topic_functions", "name": "Functions", "type": "topic"}
                ]
            }
        },
        "student": {
            "student_id": "STU-TEST-CONNECTIVITY",
            "student_name": "Connectivity Test Student",
            "learner_profile": {
                "vark": {"vark_visual": 0.8, "vark_aural": 0.3, "vark_read_write": 0.5, "vark_kinesthetic": 0.2},
                "motivation": {"intrinsic_motivation": 0.7, "extrinsic_motivation": 0.4},
                "self_regulation": {"goal_setting": 0.8, "planning": 0.6}
            },
            "knowledge_profile": {
                "domain_id": "python",
                "overall_mastery": 0.35,
                "areas": [
                    {"id": "topic_variables", "name": "Variables", "type": "topic", "mastery": 0.60},
                    {"id": "topic_loops", "name": "Loops", "type": "topic", "mastery": 0.20},
                    {"id": "topic_functions", "name": "Functions", "type": "topic", "mastery": 0.25}
                ]
            }
        }
    }

    print("\n[AI DEBUG] Calling GeminiAIProvider.generate_structured_recommendation()...")
    provider = GeminiAIProvider(api_key=api_key)

    try:
        rec = provider.generate_structured_recommendation(test_input)
        print("\n" + "=" * 60)
        print("CONNECTIVITY TEST RESULT: SUCCESS (HTTP 200 OK)")
        print("=" * 60)
        print(f" - Model Used: {rec.get('_model_name')}")
        print(f" - Domain: {rec.get('domain', {}).get('name')}")
        print(f" - Executive Summary: {rec.get('summary')[:120]}...")
        print(f" - Overall Mastery (DB Overridden): {rec.get('overall_mastery') * 100}%")
        print(f" - Priority Areas Count: {len(rec.get('priority_areas', []))}")
        print(f" - Learning Sequence Steps: {len(rec.get('learning_sequence', []))}")
        print(f" - Curated Resources Count: {len(rec.get('resources', []))}")
        print(f" - Practice Recommendations Count: {len(rec.get('practice_recommendations', []))}")
        
        print("\nPriority Areas Generated by AI:")
        for area in rec.get('priority_areas', []):
            print(f"   * {area.get('area_name')} (Mastery: {int(area.get('mastery', 0) * 100)}%): {area.get('reason')}")

        return True
    except AIGenerationError as e:
        print(f"\n[AI ERROR] AIGenerationError raised: {e.code} - {e.message}")
        return False
    except Exception as e:
        print(f"\n[AI ERROR] Unexpected Exception: {e}")
        return False

if __name__ == "__main__":
    success = test_provider_connectivity()
    if not success:
        sys.exit(1)
